```{r global_options, message = FALSE}
library(knitr) # enables knit output formatting
  opts_chunk$set(fig.align="center", fig.height=3, fig.width=4) # format knit output
library(tidyverse) # contains ggplot2, dplyr, tidyr, readr, stringr, etc
  theme_set(theme_bw(base_size = 12)) # set default plot theme for ggplot2
library(ggrepel) # enables dynamic plot labeling
library(ggthemes) # enables colorblind-friendly color palette
library(scales) # imports function show_col() for displaying color palettes
library(janitor) # imports function clean_names() for auto-formatting bad column names
```

```{r message = FALSE, fig.height=5, fig.width=8}
# custom qualitative color palettes
palette_pretty <- c("#009E24", "#0072B2","#E69F00", "#FF0000",
                    "#979797", "#5530AA", "#1E1E1E")
palette_colorblind <- c("#E69F00", "#56B4E9", "#009E73","#F0E442", 
                        "#0072B2", "#D55E00", "#CC79A7", "#999999")
palette_cb_ext <- c("#ebac23", "#b80058",  "#008cf9", "#006e00", "#00bbad",
                    "#d163e6", "#b24502", "#ff9287", "#5954d6", "#00c6f8",
                    "#878500", "#00a76c", "#979797", "#1e1e1e")
palette_npg <- c("#E64B35", "#4DBBD5", "#00A087", "#3C5488",
                 "#F39B7F", "#8491B4", "#91D1C2", "#DC0000",
                 "#7E6148", "#B09C85")

par(mfrow=c(2,2)) # output color previews on 2 lines
show_col(palette_pretty) # pretty palette
show_col(palette_colorblind) # colorblind-friendly palette
show_col(palette_cb_ext) # extended colorblind-friendly palette
show_col(palette_npg) # nature publishing group palette
```

```{r include = FALSE}
par(mfrow = c(1,1)) # reset plot output formatting
```

# Annotate CFMS complexes
**01-17-2023**

------

This document contains research notes and code generated by:

> **Rachael M. Cox**  
> Biochemistry PhD Candidate  
> University of Texas at Austin  
> rachaelcox@utexas.edu  

------

## Load data

```{r}
current <- read_csv('../ppi_ml/results/ppi_clustering/leca_clustering_cmplx_annots_011723.csv')
```

```{r}
# R code
```

## Join annotations

```{r}
# R code
```

```{r}
# R code
```

